name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
#  setup-router:
#    timeout-minutes: 5
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3

  build-products:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./products-subgraph

    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Build products subgraph with Gradle
        run: ./gradlew clean build


  build-reviews:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./reviews-subgraph

    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Build products subgraph with Gradle
        run: ./gradlew clean build

#  build-supergraph:
#    timeout-minutes: 5
#    runs-on: ubuntu-latest
#    needs: [setup-router, build-products, build-supergraph]
#
#    steps:
#      - uses: actions/checkout@v3
#
#  test:
#    timeout-minutes: 10
#    runs-on: ubuntu-latest
#    needs: build-supergraph
#
#    steps:
#      - uses: actions/checkout@v3
